// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqUxLmH8YSQh8JO1MBnqLZqbBU3UxU9mw',
    appId: '1:709638402409:web:83a57e9c863c334db78df8',
    messagingSenderId: '709638402409',
    projectId: 'dalel-app',
    authDomain: 'dalel-app.firebaseapp.com',
    storageBucket: 'dalel-app.appspot.com',
    measurementId: 'G-LQM2WJKHRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOLXxSWr-tJIisd1CkvUAmaR-Rza01VnQ',
    appId: '1:709638402409:android:6039454b1d347624b78df8',
    messagingSenderId: '709638402409',
    projectId: 'dalel-app',
    storageBucket: 'dalel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBglJ8lIleSz7XnTLgbkJiUVk0FuQzeCns',
    appId: '1:709638402409:ios:ea6a079629361710b78df8',
    messagingSenderId: '709638402409',
    projectId: 'dalel-app',
    storageBucket: 'dalel-app.appspot.com',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBglJ8lIleSz7XnTLgbkJiUVk0FuQzeCns',
    appId: '1:709638402409:ios:6cd795406743efd7b78df8',
    messagingSenderId: '709638402409',
    projectId: 'dalel-app',
    storageBucket: 'dalel-app.appspot.com',
    iosBundleId: 'com.example.dalelApp.RunnerTests',
  );
}
